### ISSUE TITLE
Error after installation via pip

### ISSUE THREAD

**Issue by bradkyle** [dmlc/tensorboard#42]
I have recently attempted to install [tensorboard](https://github.com/dmlc/tensorboard/) via pip as detailed in the README.md. The installation was deemed successful however when I try to run tensorboard after the installation, I keep on recieving an undefined symbol error as seen below.
```
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/tensorboard/tensorboard.py", line 32, in <module>
    from tensorflow.python.summary import event_file_inspector as efi
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/summary/event_file_inspector.py", line 122, in <module>
    from tensorflow.python.platform import gfile
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/platform/gfile.py", line 22, in <module>
    from tensorflow.python.lib.io.file_io import copy as Copy
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 27, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyBytes_AsStringAndSize
```
`
Have I missed something in the installation process?
What can I do to fix this?

Thanks

**Comment by zihaolucky** [comment]
Could you tell me the version? Is it `1.0.0a6` or `1.0.0a7`? In general it's already usable after `pip install tensorboard`

**Comment by bradkyle** [comment]
Hi, thanks for the response.
I am using Version: 1.0.0a6
Let me know if there is anything else you need.

**Comment by zihaolucky** [comment]
@bradkyle Could you try to build from source?  Seems the wrapper doesn't build correctly in Python3.5 `python/_pywrap_tensorflow.so: undefined symbol: PyBytes_AsStringAndSize`

**Comment by Hskye** [comment]
Maybe you can try sudo pip install tensorflow.tensorboard.

**Comment by skulhare** [comment]
Hi, I am facing the same issue. 
@Hskye, I tried installing tensorflow.tensorboard but it throwing this error: 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tensorflow.tensorboard .dist-info directory not found

I am using python 3.5 and I installed tensorflow from pip3. 

Thanks in advance.

**Comment by huevosabio** [comment]
Hi all, 
I'm facing the same issue.  Also, Python 3.5.

**Comment by daxaxelrod** [comment]
Hi! Same issue here. Symbol not found: _PyBytes_AsString

**Comment by samehraban** [comment]
Hi all,
I'm facing the same issue. Also, Python 3.5.

**Comment by arwer13** [comment]
Hi, I'm having the same issue with python 3.4.3 on Ubuntu 14.04.5 LTS.
The trick supposed by @daxaxelrod helped, for me it's:

    python3 /usr/local/lib/python3.4/dist-packages/tensorboard/main.py --logdir=./logs

**Comment by zuoanqh** [comment]
same issue, python3.5.4, tensorboard a6, WSL.

**Comment by lwilson** [comment]
It looks like the issue is related to finding the python executable in the wrapper script (`/usr/bin/tensorboard`, line 48):
```python
return SearchPath('python')
```
On systems where there is a default python2 installation, this will load python2, even if you have python3 installed (often called python3).  When I print out `args` just before the `try` block on line 139 it returns:
```python
['/usr/bin/python2.7', '/usr/lib/python3.4/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/tensorboard/tensorboard.py']
```
If I alter line 48 to search for python3 (instead of python), then tensorboard runs without issue.
