### ISSUE TITLE
Error from pip install

### ISSUE THREAD

**Issue by botev** [dmlc/tensorboard#53]
Hi, so recently trying to install from `pip install` when I try running tensorboard from the command line I get:
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/tensorboard/tensorboard.py", line 32, in <module>
    from tensorflow.python.summary import event_file_inspector as efi
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/summary/event_file_inspector.py", line 122, in <module>
    from tensorflow.python.platform import gfile
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/platform/gfile.py", line 22, in <module>
    from tensorflow.python.lib.io.file_io import copy as Copy
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 27, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
SystemError: initialization of _pywrap_tensorflow raised unreported exception
```
Which version of numpy is used in the pypi package for tensorboard?

**Comment by zihaolucky** [comment]
Seems we have some problems with Python3.6, there're some issues about this. Did you try another Python version?

**Comment by botev** [comment]
Unfortunately, this anaconda is my only option as I'm on a department cluster. I also tried building from source, but since they have already changed the tensorflow repo that does not work either. Do you know which is the last working tag/commit from tensorflow for which I can build tensorboard with?

**Comment by zihaolucky** [comment]
@botev I have fixed the backend and the install script. https://github.com/dmlc/tensorboard/blob/master/installer.sh#L9

**Comment by botev** [comment]
Hmm, is there anything specific that I need to change during installation. When I run the build script after bazel I get:
```
Requirement 'python/dist/*.whl' looks like a filename, but the file does not exist
```
and there does not seem to be an wheels in `python/dist`

**Comment by zihaolucky** [comment]
Could you tell me how to reproduce this? I will look into this.

**Comment by botev** [comment]
So I just cloned the repo. Than did this and the output is:
```
$chmod +x installer.sh
$./installer.sh
protoc tensorboard/src/*.proto --python_out=python/
Cloning into 'tensorflow'...
remote: Counting objects: 225876, done.
remote: Total 225876 (delta 0), reused 0 (delta 0), pack-reused 225876
Receiving objects: 100% (225876/225876), 117.86 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (174956/174956), done.
Switched to a new branch 'v1.0.0-rc1'
Please specify the location of python. [Default is /opt/anaconda3/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /home/alex/work/python/data-sets
  /home/alex/work/python/Lasagne
  /home/alex/work/python/LaplaceNets
  /home/alex/work/python/Theano
  /opt/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/alex/work/python/data-sets]
/opt/anaconda3/lib/python3.6/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
Configuration finished
... BAZEL BUILDS ....
Requirement 'python/dist/*.whl' looks like a filename, but the file does not exist
*.whl is not a valid wheel filename.
Now you can remove tensorflow with rm -rf tensorflow
```
Where are the wheels suppose to be at the end of the bazel build?

**Comment by zihaolucky** [comment]
Did the bazel build success? Let me try this in my env.

**Comment by botev** [comment]
I think so because `tensorboard/python/tensorboard/tensorboard` is a working tensorboard which I can run. I guess there something fishy going with the wheels. If you don't get it its fine, since I can just modify the source and use that.

**Comment by zihaolucky** [comment]
I failed to reproduce this in Python2.7, let me try in Python3.6 later.

**Comment by botev** [comment]
Sure if you need some more info let me know, just note that my python 3.6 is actually under anaconda. That should not matter, but I have experienced cases where it does.
